--  Todo API
--  Todo API
--
--  OpenAPI spec version: 1.0.0
--  Contact: Stephane.Carrez@gmail.com
--
--  NOTE: This package is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
--  https://github.com/swagger-api/swagger-codegen.git
--  Do not edit the class manually.
package body Todos.Servers is

   --  Create a todo
   --  
   procedure Create_Todo (Title : in Swagger.UString) is
   begin
      null;
   end Create_Todo;

   --  Delete the todo
   --  Supprime le test/travail soit avant son execution, soit après son execution. 
   procedure Delete_Todo (Todo_Id : in Swagger.Long) is
   begin
      null;
   end Delete_Todo;

   --  List the available tasks
   --  List the available tasks 
   procedure List_Todos (Status : in Swagger.UString) is
   begin
      null;
   end List_Todos;

   --  Update the todo
   --  Update the todo title and status 
   procedure Update_Todo (Todo_Id : in Swagger.Long;
      Title : in Swagger.UString;
      Status : in Swagger.UString) is
   begin
      null;
   end Update_Todo;

   --  Create a new user
   --  Create a new user
   procedure Users_Post (Username : in Swagger.UString) is
   begin
      null;
   end Users_Post;
end Todos.Servers;
