--  Todo API
--  Todo API
--
--  The version of the OpenAPI document: 1.0.0
--  Contact: Stephane.Carrez@gmail.com
--
--  NOTE: This package is auto generated by OpenAPI-Generator 5.0.0-SNAPSHOT.
--  https://openapi-generator.tech
--  Do not edit the class manually.

with Swagger.Servers;
with Todos.Models;
with Security.Permissions;
package Todos.Skeletons is
   use Todos.Models;
   type Server_Type is limited interface;

   --  Write a todo
   package ACL_Write_Todo is new Security.Permissions.Definition ("write:todo");

   --  Read a todo
   package ACL_Read_Todo is new Security.Permissions.Definition ("read:todo");



   --  Create a todo
   procedure Create_Todo
      (Server : in out Server_Type;
       Title : in Swagger.UString;
       Result  : out Todos.Models.Todo_Type;
       Context : in out Swagger.Servers.Context_Type) is abstract;

   --  Delete the todo
   --  Delete the todo
   procedure Delete_Todo
      (Server : in out Server_Type;
       Todo_Id : in Swagger.Long;
       Context : in out Swagger.Servers.Context_Type) is abstract;

   --  List the available tasks
   --  The list of tasks can be filtered by their status.
   procedure List_Todos
      (Server : in out Server_Type;
       Status : in Swagger.Nullable_UString;
       Result  : out Todos.Models.Todo_Type_Vectors.Vector;
       Context : in out Swagger.Servers.Context_Type) is abstract;

   --  Update the todo
   --  Update the todo title and status
   procedure Update_Todo
      (Server : in out Server_Type;
       Todo_Id : in Swagger.Long;
       Title : in Swagger.Nullable_UString;
       Status : in Swagger.Nullable_UString;
       Result  : out Todos.Models.Todo_Type;
       Context : in out Swagger.Servers.Context_Type) is abstract;

   generic
      type Implementation_Type is limited new Server_Type with private;
      URI_Prefix : String := "";
   package Skeleton is

      procedure Register (Server : in out Swagger.Servers.Application_Type'Class);


      --  Create a todo
      procedure Create_Todo
         (Req     : in out Swagger.Servers.Request'Class;
          Reply   : in out Swagger.Servers.Response'Class;
          Stream  : in out Swagger.Servers.Output_Stream'Class;
          Context : in out Swagger.Servers.Context_Type);


      --  Delete the todo
      procedure Delete_Todo
         (Req     : in out Swagger.Servers.Request'Class;
          Reply   : in out Swagger.Servers.Response'Class;
          Stream  : in out Swagger.Servers.Output_Stream'Class;
          Context : in out Swagger.Servers.Context_Type);


      --  List the available tasks
      procedure List_Todos
         (Req     : in out Swagger.Servers.Request'Class;
          Reply   : in out Swagger.Servers.Response'Class;
          Stream  : in out Swagger.Servers.Output_Stream'Class;
          Context : in out Swagger.Servers.Context_Type);


      --  Update the todo
      procedure Update_Todo
         (Req     : in out Swagger.Servers.Request'Class;
          Reply   : in out Swagger.Servers.Response'Class;
          Stream  : in out Swagger.Servers.Output_Stream'Class;
          Context : in out Swagger.Servers.Context_Type);

   end Skeleton;

   generic
      type Implementation_Type is limited new Server_Type with private;
      URI_Prefix : String := "";
   package Shared_Instance is

      procedure Register (Server : in out Swagger.Servers.Application_Type'Class);


      --  Create a todo
      procedure Create_Todo
         (Req     : in out Swagger.Servers.Request'Class;
          Reply   : in out Swagger.Servers.Response'Class;
          Stream  : in out Swagger.Servers.Output_Stream'Class;
          Context : in out Swagger.Servers.Context_Type);


      --  Delete the todo
      procedure Delete_Todo
         (Req     : in out Swagger.Servers.Request'Class;
          Reply   : in out Swagger.Servers.Response'Class;
          Stream  : in out Swagger.Servers.Output_Stream'Class;
          Context : in out Swagger.Servers.Context_Type);


      --  List the available tasks
      procedure List_Todos
         (Req     : in out Swagger.Servers.Request'Class;
          Reply   : in out Swagger.Servers.Response'Class;
          Stream  : in out Swagger.Servers.Output_Stream'Class;
          Context : in out Swagger.Servers.Context_Type);


      --  Update the todo
      procedure Update_Todo
         (Req     : in out Swagger.Servers.Request'Class;
          Reply   : in out Swagger.Servers.Response'Class;
          Stream  : in out Swagger.Servers.Output_Stream'Class;
          Context : in out Swagger.Servers.Context_Type);


   private
      protected Server is

         --  Create a todo
         procedure Create_Todo
            (Title : in Swagger.UString;
             Result  : out Todos.Models.Todo_Type;
             Context : in out Swagger.Servers.Context_Type);

         --  Delete the todo
         procedure Delete_Todo
            (Todo_Id : in Swagger.Long;
             Context : in out Swagger.Servers.Context_Type);

         --  List the available tasks
         procedure List_Todos
            (Status : in Swagger.Nullable_UString;
             Result  : out Todos.Models.Todo_Type_Vectors.Vector;
             Context : in out Swagger.Servers.Context_Type);

         --  Update the todo
         procedure Update_Todo
            (Todo_Id : in Swagger.Long;
             Title : in Swagger.Nullable_UString;
             Status : in Swagger.Nullable_UString;
             Result  : out Todos.Models.Todo_Type;
             Context : in out Swagger.Servers.Context_Type);

      private
         Impl : Implementation_Type;
      end Server;
   end Shared_Instance;

end Todos.Skeletons;
