description = "Todo API Server"
name = "todos"
version = "1.1.0"
authors = ["Stephane.Carrez@gmail.com"]
licenses = "Apache-2.0"
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = ["todos.gpr"]
tags = ["web", "openapi", "demo"]
executables = ["todos_aws", "todos-client"]

[[depends-on]]
openapi_server = "~0.7.0"
servletada_aws = "any"
utilada = "^2.7.0"
utilada_xml = "^2.7.0"
utilada_aws = "^2.7.0"
aws = "^23.0"

[configuration]
disabled = true
